// AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_CONFIRM = 'REGISTER_CONFIRM';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// MOVIE TYPES
export const GET_MOVIES_BEGIN = 'GET_MOVIES_BEGIN';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_HORROR_SUCCESS = 'GET_HORROR_SUCCESS';
export const GET_DRAMA_SUCCESS = 'GET_DRAMA_SUCCESS';
export const GET_FANTASY_SUCCESS = 'GET_FANTASY_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';

// PROFILE TYPES
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const FILL_USER_LIKES = 'FILL_USER_LIKES';
